"""Compatibility shim for batch generation entry service.

Deprecated: import from app.services.compat.batch_generation_entry_compat_service instead.
"""

from __future__ import annotations

from typing import Any, Dict, Optional

from app.services.compat import batch_generation_entry_compat_service as _impl
from app.services.chapter_quality_context_service import StoryPacket
from app.services.story_repair_payload_service import StoryRepairPayload

execute_batch_generation_in_order_with_default_wiring = _impl.execute_batch_generation_in_order_with_default_wiring
generate_single_chapter_for_batch_with_default_wiring = _impl.generate_single_chapter_for_batch_with_default_wiring


async def execute_batch_generation_in_order(
    *,
    batch_id: str,
    user_id: str,
    ai_service,
    custom_model: Optional[str] = None,
    temp_narrative_perspective: Optional[str] = None,
    story_packet: Optional[StoryPacket] = None,
    creative_mode: Optional[str] = None,
    story_focus: Optional[str] = None,
    plot_stage: Optional[str] = None,
    story_creation_brief: Optional[str] = None,
    quality_preset: Optional[str] = None,
    quality_notes: Optional[str] = None,
    enable_web_research: Optional[bool] = None,
    web_research_query: Optional[str] = None,
    story_repair_summary: Optional[str] = None,
    story_repair_targets: Optional[list[str]] = None,
    story_preserve_strengths: Optional[list[str]] = None,
    story_repair_payload: Optional[StoryRepairPayload] = None,
    base_quality_profile: Optional[Dict[str, Any]] = None,
    get_db_write_lock_fn=None,
    run_generation_fn=None,
    await_generation_result_fn=None,
    run_batch_analysis_fn=None,
    resolve_story_repair_state_fn=None,
    sync_task_story_repair_state_fn=None,
    publish_task_stream_event_fn=None,
):
    return await execute_batch_generation_in_order_with_default_wiring(
        batch_id=batch_id,
        user_id=user_id,
        ai_service=ai_service,
        custom_model=custom_model,
        temp_narrative_perspective=temp_narrative_perspective,
        story_packet=story_packet,
        creative_mode=creative_mode,
        story_focus=story_focus,
        plot_stage=plot_stage,
        story_creation_brief=story_creation_brief,
        quality_preset=quality_preset,
        quality_notes=quality_notes,
        enable_web_research=enable_web_research,
        web_research_query=web_research_query,
        story_repair_summary=story_repair_summary,
        story_repair_targets=story_repair_targets,
        story_preserve_strengths=story_preserve_strengths,
        story_repair_payload=story_repair_payload,
        base_quality_profile=base_quality_profile,
        get_db_write_lock_fn=get_db_write_lock_fn,
        run_generation_fn=run_generation_fn,
        await_generation_result_fn=await_generation_result_fn,
        run_batch_analysis_fn=run_batch_analysis_fn,
        resolve_story_repair_state_fn=resolve_story_repair_state_fn,
        sync_task_story_repair_state_fn=sync_task_story_repair_state_fn,
        publish_task_stream_event_fn=publish_task_stream_event_fn,
    )


async def generate_single_chapter_for_batch(
    *,
    db_session,
    chapter,
    user_id: str,
    style_id: Optional[int],
    target_word_count: int,
    ai_service,
    write_lock,
    story_packet: Optional[StoryPacket] = None,
    base_quality_profile: Optional[Dict[str, Any]] = None,
    custom_model: Optional[str] = None,
    previous_summary_context: Optional[str] = None,
    temp_narrative_perspective: Optional[str] = None,
    creative_mode: Optional[str] = None,
    story_focus: Optional[str] = None,
    plot_stage: Optional[str] = None,
    story_creation_brief: Optional[str] = None,
    quality_preset: Optional[str] = None,
    quality_notes: Optional[str] = None,
    enable_web_research: Optional[bool] = None,
    web_research_query: Optional[str] = None,
    story_repair_summary: Optional[str] = None,
    story_repair_targets: Optional[list[str]] = None,
    story_preserve_strengths: Optional[list[str]] = None,
    story_repair_payload: Optional[StoryRepairPayload] = None,
    active_story_repair_snapshot: Optional[Dict[str, Any]] = None,
    story_repair_state: Optional[Dict[str, Any]] = None,
    stream_task_id: Optional[str] = None,
    stream_chunks: bool = False,
    retry_count: int = 0,
    max_retries: int = 1,
    candidate_generator_fn=None,
    default_candidate_limit: int = 2,
    heartbeat_interval_seconds: float = 10.0,
    chapter_web_research_service=None,
    publish_task_stream_event_fn=None,
    resolve_quality_profile_fn=None,
    one_to_one_builder_cls=None,
    one_to_many_builder_cls=None,
    get_template_fn=None,
    format_prompt_fn=None,
    build_runtime_system_prompt_fn=None,
    compute_story_quality_metrics_fn=None,
    resolve_quality_gate_execution_plan_fn=None,
):
    return await generate_single_chapter_for_batch_with_default_wiring(
        db_session=db_session,
        chapter=chapter,
        user_id=user_id,
        style_id=style_id,
        target_word_count=target_word_count,
        ai_service=ai_service,
        write_lock=write_lock,
        story_packet=story_packet,
        base_quality_profile=base_quality_profile,
        custom_model=custom_model,
        previous_summary_context=previous_summary_context,
        temp_narrative_perspective=temp_narrative_perspective,
        creative_mode=creative_mode,
        story_focus=story_focus,
        plot_stage=plot_stage,
        story_creation_brief=story_creation_brief,
        quality_preset=quality_preset,
        quality_notes=quality_notes,
        enable_web_research=enable_web_research,
        web_research_query=web_research_query,
        story_repair_summary=story_repair_summary,
        story_repair_targets=story_repair_targets,
        story_preserve_strengths=story_preserve_strengths,
        story_repair_payload=story_repair_payload,
        active_story_repair_snapshot=active_story_repair_snapshot,
        story_repair_state=story_repair_state,
        stream_task_id=stream_task_id,
        stream_chunks=stream_chunks,
        retry_count=retry_count,
        max_retries=max_retries,
        candidate_generator_fn=candidate_generator_fn,
        default_candidate_limit=default_candidate_limit,
        heartbeat_interval_seconds=heartbeat_interval_seconds,
        chapter_web_research_service=chapter_web_research_service,
        publish_task_stream_event_fn=publish_task_stream_event_fn,
        resolve_quality_profile_fn=resolve_quality_profile_fn,
        one_to_one_builder_cls=one_to_one_builder_cls,
        one_to_many_builder_cls=one_to_many_builder_cls,
        get_template_fn=get_template_fn,
        format_prompt_fn=format_prompt_fn,
        build_runtime_system_prompt_fn=build_runtime_system_prompt_fn,
        compute_story_quality_metrics_fn=compute_story_quality_metrics_fn,
        resolve_quality_gate_execution_plan_fn=resolve_quality_gate_execution_plan_fn,
    )
