"""Compatibility shim for story quality feedback service.

Deprecated: import from app.services.quality_domain.story_quality_feedback_service instead.
"""

from app.services.quality_domain.story_quality_feedback_service import *  # noqa: F401,F403
from app.services.quality_domain import story_quality_feedback_service as _impl

_calc_cliffhanger_rate = _impl._calc_cliffhanger_rate
_calc_conflict_chain_rate = _impl._calc_conflict_chain_rate
_calc_dialogue_naturalness_rate = _impl._calc_dialogue_naturalness_rate
_calc_opening_hook_rate = _impl._calc_opening_hook_rate
_calc_outline_alignment_rate = _impl._calc_outline_alignment_rate
_calc_payoff_chain_rate = _impl._calc_payoff_chain_rate
_calc_rule_grounding_rate = _impl._calc_rule_grounding_rate
_expand_anchor_match_tokens = _impl._expand_anchor_match_tokens
_extract_dialogue_segments = _impl._extract_dialogue_segments
_extract_outline_anchor_tokens = _impl._extract_outline_anchor_tokens
_extract_outline_rule_hints = _impl._extract_outline_rule_hints
_extract_payoff_chain_hints = _impl._extract_payoff_chain_hints
_extract_rule_keywords = _impl._extract_rule_keywords
_normalize_world_rules_text = _impl._normalize_world_rules_text
_resolve_rule_grounding_source_text = _impl._resolve_rule_grounding_source_text
