"""添加API兼容性字段

Revision ID: 20260222_api_compat
Revises: d887fd1a30a6
Create Date: 2026-02-22 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260222_api_compat'
down_revision: Union[str, None] = 'd887fd1a30a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('api_backup_urls', sa.Text(), nullable=True, comment='备用API地址列表(JSON)'))
    op.add_column('settings', sa.Column('provider_type', sa.String(length=50), nullable=True, server_default='openai', comment='Provider类型(openai/azure/newapi/custom)'))
    op.add_column('settings', sa.Column('fallback_strategy', sa.String(length=20), nullable=True, server_default='auto', comment='端点切换策略(auto/manual)'))
    op.add_column('settings', sa.Column('azure_api_version', sa.String(length=50), nullable=True, comment='Azure API版本'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'azure_api_version')
    op.drop_column('settings', 'fallback_strategy')
    op.drop_column('settings', 'provider_type')
    op.drop_column('settings', 'api_backup_urls')
    # ### end Alembic commands ###
